CONFIG upgrade babel preset env to run with node 12.18 was getting this error when trying to do production build $ webpack --mode production  --config webpack.config.build.js Hash: d573ae8978f62f9fb56a Version: webpack 4.29.6 Time: 728ms Built at: 09/16/2020 10:20:22 AM  1 asset Entrypoint main = index.js [0] ./src/lib/TimeLine.js 7.34 KiB {0} [built] [failed] [1 error]
ERROR in ./src/lib/TimeLine.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/runner/.cache/yarn/v6/.tmp/c6fbc2168a7857db4e6d0eea14e4f947.49889cc9cddef63454c255a7894a75fc88cb85a8.prepare/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/runner/.cache/yarn/v6/.tmp/c6fbc2168a7857db4e6d0eea14e4f947.49889cc9cddef63454c255a7894a75fc88cb85a8.prepare/node_modules/@babel/preset-env/lib/index.js
- /home/runner/.cache/yarn/v6/.tmp/c6fbc2168a7857db4e6d0eea14e4f947.49889cc9cddef63454c255a7894a75fc88cb85a8.prepare/node_modules/@babel/core/lib/config/files/plugins.js
- /home/runner/.cache/yarn/v6/.tmp/c6fbc2168a7857db4e6d0eea14e4f947.49889cc9cddef63454c255a7894a75fc88cb85a8.prepare/node_modules/@babel/core/lib/config/files/index.js
- /home/runner/.cache/yarn/v6/.tmp/c6fbc2168a7857db4e6d0eea14e4f947.49889cc9cddef63454c255a7894a75fc88cb85a8.prepare/node_modules/@babel/core/lib/index.js
- /home/runner/.cache/yarn/v6/.tmp/c6fbc2168a7857db4e6d0eea14e4f947.49889cc9cddef63454c255a7894a75fc88cb85a8.prepare/node_modules/babel-loader/lib/index.js